// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateAWGInterface(arg1) {
  return window['go']['main']['App']['ActivateAWGInterface'](arg1);
}

export function ConfigureAWGInterface(arg1, arg2) {
  return window['go']['main']['App']['ConfigureAWGInterface'](arg1, arg2);
}

export function CreateAWGInterface(arg1) {
  return window['go']['main']['App']['CreateAWGInterface'](arg1);
}

export function GetRouterWebURL(arg1) {
  return window['go']['main']['App']['GetRouterWebURL'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ValidateAWGConfig(arg1, arg2) {
  return window['go']['main']['App']['ValidateAWGConfig'](arg1, arg2);
}

export function ValidateRouterConfig(arg1) {
  return window['go']['main']['App']['ValidateRouterConfig'](arg1);
}
