// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAWGConnection(arg1, arg2) {
  return window['go']['main']['App']['CreateAWGConnection'](arg1, arg2);
}

export function GetRouterWebURL(arg1) {
  return window['go']['main']['App']['GetRouterWebURL'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ValidateRouterConfig(arg1) {
  return window['go']['main']['App']['ValidateRouterConfig'](arg1);
}
