// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateAWGConnection(arg1:main.RouterConfig,arg2:main.AWGConfig):Promise<void>;

export function GetRouterWebURL(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ValidateRouterConfig(arg1:main.RouterConfig):Promise<void>;
